import { ImageResponse } from "next/og";

/**
 * Site-wide fallback OG image. 1200×630 PNG generated by Next.js at
 * build time and cached at the edge. Pages can override by exporting
 * their own `opengraph-image` or by setting `openGraph.images` in
 * their `metadata` block.
 *
 * No DB / network calls inside — keeps the build deterministic and
 * lets the image stay statically cached forever (purged via redeploy).
 */

export const alt = "Toplisters.xyz — Jobs, mapped to the world";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function OpengraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background:
            "radial-gradient(circle at 30% 20%, #1e293b 0%, #0a0e1a 60%, #050714 100%)",
          color: "white",
          padding: 80,
          fontFamily: "sans-serif",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 16,
            fontSize: 28,
            letterSpacing: "0.02em",
            opacity: 0.6,
          }}
        >
          <span
            style={{
              display: "flex",
              width: 12,
              height: 12,
              borderRadius: 999,
              background: "linear-gradient(135deg, #38bdf8, #fb923c)",
            }}
          />
          <span>toplisters.xyz</span>
        </div>

        <div style={{ display: "flex", flexDirection: "column" }}>
          <div
            style={{
              fontSize: 104,
              fontWeight: 700,
              lineHeight: 1.02,
              letterSpacing: "-0.03em",
            }}
          >
            Jobs, mapped
          </div>
          <div
            style={{
              fontSize: 104,
              fontWeight: 700,
              lineHeight: 1.02,
              letterSpacing: "-0.03em",
              background: "linear-gradient(90deg, #38bdf8, #fb923c)",
              backgroundClip: "text",
              color: "transparent",
            }}
          >
            to the world.
          </div>
          <div
            style={{
              fontSize: 32,
              opacity: 0.65,
              marginTop: 28,
              lineHeight: 1.35,
              maxWidth: 880,
            }}
          >
            An interactive 3D globe job board — discover roles by clicking your
            region. Blue-collar to white-collar, free to post.
          </div>
        </div>

        <div
          style={{
            display: "flex",
            gap: 40,
            fontSize: 22,
            opacity: 0.7,
            letterSpacing: "0.01em",
          }}
        >
          <span>Global coverage</span>
          <span>·</span>
          <span>Updated daily</span>
          <span>·</span>
          <span>Source-attributed</span>
        </div>
      </div>
    ),
    size,
  );
}
