import { ImageResponse } from "next/og";

/**
 * Site-wide fallback OG image. 1200×630 PNG generated by Next.js at
 * build time and cached at the edge. Pages can override by exporting
 * their own `opengraph-image` or by setting `openGraph.images` in
 * their `metadata` block.
 *
 * No DB / network calls inside — keeps the build deterministic and
 * lets the image stay statically cached forever (purged via redeploy).
 */

export const alt = "Toplisters.xyz — Jobs, mapped to the world";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function OpengraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: "#0E1116",
          color: "#F6F4EE",
          padding: 80,
          fontFamily: "sans-serif",
        }}
      >
        {/* Brand mark — three-bar list icon */}
        <div style={{ display: "flex", alignItems: "center", gap: 24 }}>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              alignItems: "flex-start",
              gap: 6,
              width: 88,
              height: 88,
              borderRadius: 20,
              background: "#0E1116",
              border: "1.5px solid rgba(246,244,238,0.18)",
              padding: 18,
            }}
          >
            <span style={{ display: "flex", width: 52, height: 10, borderRadius: 3, background: "#1F6FEB" }} />
            <span style={{ display: "flex", width: 36, height: 10, borderRadius: 3, background: "rgba(246,244,238,0.85)" }} />
            <span style={{ display: "flex", width: 26, height: 10, borderRadius: 3, background: "rgba(246,244,238,0.55)" }} />
          </div>
          <div
            style={{
              display: "flex",
              fontSize: 38,
              fontWeight: 700,
              letterSpacing: "-0.025em",
            }}
          >
            toplisters
            <span style={{ display: "flex", color: "#1F6FEB" }}>.</span>
          </div>
        </div>

        <div style={{ display: "flex", flexDirection: "column" }}>
          <div
            style={{
              fontSize: 108,
              fontWeight: 700,
              lineHeight: 1.02,
              letterSpacing: "-0.035em",
              display: "flex",
            }}
          >
            Jobs, mapped
          </div>
          <div
            style={{
              fontSize: 108,
              fontWeight: 700,
              lineHeight: 1.02,
              letterSpacing: "-0.035em",
              color: "#1F6FEB",
              display: "flex",
            }}
          >
            to the world.
          </div>
          <div
            style={{
              fontSize: 32,
              opacity: 0.7,
              marginTop: 28,
              lineHeight: 1.35,
              maxWidth: 920,
              display: "flex",
            }}
          >
            An interactive 3D globe job board — discover roles by clicking your
            region. Blue-collar to white-collar, free to post.
          </div>
        </div>

        <div
          style={{
            display: "flex",
            gap: 32,
            fontSize: 22,
            opacity: 0.75,
            letterSpacing: "0.01em",
            alignItems: "center",
          }}
        >
          <span style={{ display: "flex" }}>Global coverage</span>
          <span style={{ display: "flex", opacity: 0.4 }}>·</span>
          <span style={{ display: "flex" }}>Updated daily</span>
          <span style={{ display: "flex", opacity: 0.4 }}>·</span>
          <span style={{ display: "flex" }}>Source-attributed</span>
        </div>
      </div>
    ),
    size,
  );
}
